- name: dispatch component
  hosts: dispatch
  become: yes

  tasks:
  - name: install golang
    ansible.builtin.dnf:
      name: golang
      state: present
  
  - name: create roboshop user
    ansible.builtin.user:
      name: roboshop
  
  - name: Recursively removing directory
    ansible.builtin.file:
      path: /app
      state: absent
      
  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download app code
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/dispatch.zip
      dest: /tmp
  
  - name: extract app code
    ansible.builtin.unarchive:
      src: /tmp/dispatch.zip
      dest: /app
      remote_src: yes
  
  - name: download and build the sofware
    ansible.builtin.command:
      name: "{{item}}"
      state: present
    loop:
    - go mod init dispatch
    - go get 
    - go build

  - name: copy dispatch service
    ansible.builtin.copy:
      src: dispatch.service
      dest: /etc/systemd/system/dispatch.service

  - name: load and start daemon service
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: start and enable the service
    ansible.builtin.service:
      name: dispatch
      state: present
      enabled: yes


